---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository and cache
    apt:
     update_cache: yes

  - name: install 'ncdu' package on all server for disk analysis
    apt:
      name: ncdu
      state: present

- hosts: webserver
  become: true
  name: Role for webservers
  roles:
    - role: webserver

- hosts: all
  name: Create swap space on all servers
  become: true
  roles:
    - role: swapfile
